---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: insights-behavioral-spec
  namespace: obsint-processing-tenant
  annotations:
    # This stub annotation is needed until KFLUXBUGS-1300 is resolved.
    hello: world
spec:
  displayName: insights-behavioral-spec
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: insights-behavioral-spec
  namespace: obsint-processing-tenant
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
spec:
  application: insights-behavioral-spec
  componentName: insights-behavioral-spec
  source:
    git:
      revision: main
      url: https://github.com/RedHatInsights/insights-behavioral-spec
      dockerfileUrl: Dockerfile
      context: ./
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-insights-behavioral-spec-insights-behavioral-spec
  namespace: obsint-processing-tenant
  labels:
    appstudio.redhat.com/application: insights-behavioral-spec
    appstudio.redhat.com/component: insights-behavioral-spec
spec:
  image:
    name: obsint-processing-tenant/insights-behavioral-spec/insights-behavioral-spec
    visibility: public

