apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    build.appstudio.openshift.io/request: configure-pac
  name: insights-behavioral-spec
  namespace: obsint-processing-tenant
spec:
  application: insights-behavioral-spec
  componentName: insights-behavioral-spec
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile
      revision: main
      url: https://github.com/RedHatInsights/insights-behavioral-spec
